# Generated by Django 4.1.3 on 2022-12-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buyer_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='cattler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='Cattleimages')),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('cost', models.BigIntegerField()),
            ],
        ),
    ]
