# Generated by Django 4.1.3 on 2022-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cattler'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattler',
            name='status',
            field=models.CharField(choices=[(0, 'Sold'), (1, 'Purchased')], default='Sold', max_length=25),
        ),
    ]
