# Generated by Django 4.1.3 on 2022-12-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_registration_alter_cattler_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='type',
            new_name='typec',
        ),
    ]
