# Generated by Django 4.1.3 on 2022-12-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_type_registration_typec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registration',
            new_name='registration_id',
        ),
    ]
